### PR TITLE
added title attributes to track links for intuitiveness

### LINKED ISSUE #127: add title attribute to track links

### PR DESCRIPTION
**Pull request by meeday**

### CODE REVIEW

**Review by Goldenaries658 — CHANGES_REQUESTED** [review]
Not sure why but this has cause the hover on the albums to go weird

**Comment by meeday** [comment]
how is the hover weird? seems to work fine on my computer

**Comment by Goldenaries658** [comment]
Skewed  
image

**Comment by Goldenaries658** [comment]
Looks good, can you work out why long albums are shunting off to the side.

image

**Review by Goldenaries658 — APPROVED** [review]

**Pull request merged**
