### PR TITLE
search placeholder removed after enter key pressed

### LINKED ISSUE #47: Function to erase user input out after search

### PR DESCRIPTION
**Pull request by meeday**

### CODE REVIEW

**Review by Goldenaries658 — CHANGES_REQUESTED** [review]
Inconsistency: will need to do the same for when search icon is clicked and also for the album search inputs when that icon is pressed

**Comment by meeday** [comment]
I can add the code in those places as well

**Comment by Goldenaries658** [comment]
Mint, just have to be sure you're pointing to the other text boxes in the case of album searches

**Comment by meeday** [comment]
I've made the changes consistent across all types of searches

**Review by Goldenaries658 — APPROVED** [review]

**Comment by Goldenaries658** [comment]
Thanks for the formatting 👊🏾

**Pull request merged**
